Traceback (most recent call last):
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Go into first entry in list, which is the dictionary 
# Then go within id of dictionary
session_id = expt_cont[0]['id']
data = boc.get_ophys_experiment_data(session_id)

# Take a look at the kind of object data is 
print(data)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-7-452136cb431e>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;31m# Then go within id of dictionary[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0msession_id[0m [0;34m=[0m [0mexpt_cont[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[[0m[0;34m'id'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mdata[0m [0;34m=[0m [0mboc[0m[0;34m.[0m[0mget_ophys_experiment_data[0m[0;34m([0m[0msession_id[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0;31m# Take a look at the kind of object data is[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/allensdk/core/brain_observatory_cache.py[0m in [0;36mget_ophys_experiment_data[0;34m(self, ophys_experiment_id, file_name)[0m
[1;32m    487[0m         [0mself[0m[0;34m.[0m[0mapi[0m[0;34m.[0m[0msave_ophys_experiment_data[0m[0;34m([0m[0mophys_experiment_id[0m[0;34m,[0m [0mfile_name[0m[0;34m,[0m [0mstrategy[0m[0;34m=[0m[0;34m'lazy'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    488[0m [0;34m[0m[0m
[0;32m--> 489[0;31m         [0;32mreturn[0m [0mBrainObservatoryNwbDataSet[0m[0;34m([0m[0mfile_name[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    490[0m [0;34m[0m[0m
[1;32m    491[0m     [0;32mdef[0m [0mget_ophys_experiment_analysis[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mophys_experiment_id[0m[0;34m,[0m [0mstimulus_type[0m[0;34m,[0m [0mfile_name[0m[0;34m=[0m[0;32mNone[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/allensdk/core/brain_observatory_nwb_data_set.py[0m in [0;36m__init__[0;34m(self, nwb_file)[0m
[1;32m    143[0m [0;34m[0m[0m
[1;32m    144[0m         [0;32mif[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mexists[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mnwb_file[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 145[0;31m             [0mmeta[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mget_metadata[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    146[0m             [0;32mif[0m [0mmeta[0m [0;32mand[0m [0;34m'pipeline_version'[0m [0;32min[0m [0mmeta[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    147[0m                 [0mpipeline_version_str[0m [0;34m=[0m [0mmeta[0m[0;34m[[0m[0;34m'pipeline_version'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/allensdk/core/brain_observatory_nwb_data_set.py[0m in [0;36mget_metadata[0;34m(self)[0m
[1;32m    737[0m         [0mmeta[0m [0;34m=[0m [0;34m{[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[1;32m    738[0m [0;34m[0m[0m
[0;32m--> 739[0;31m         [0;32mwith[0m [0mh5py[0m[0;34m.[0m[0mFile[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mnwb_file[0m[0;34m,[0m [0;34m'r'[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    740[0m             [0;32mfor[0m [0mmemory_key[0m[0;34m,[0m [0mdisk_key[0m [0;32min[0m [0mBrainObservatoryNwbDataSet[0m[0;34m.[0m[0mFILE_METADATA_MAPPING[0m[0;34m.[0m[0mitems[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    741[0m                 [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py[0m in [0;36m__init__[0;34m(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)[0m
[1;32m    406[0m                 fid = make_fid(name, mode, userblock_size,
[1;32m    407[0m                                [0mfapl[0m[0;34m,[0m [0mfcpl[0m[0;34m=[0m[0mmake_fcpl[0m[0;34m([0m[0mtrack_order[0m[0;34m=[0m[0mtrack_order[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 408[0;31m                                swmr=swmr)
[0m[1;32m    409[0m [0;34m[0m[0m
[1;32m    410[0m             [0;32mif[0m [0misinstance[0m[0;34m([0m[0mlibver[0m[0;34m,[0m [0mtuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py[0m in [0;36mmake_fid[0;34m(name, mode, userblock_size, fapl, fcpl, swmr)[0m
[1;32m    171[0m         [0;32mif[0m [0mswmr[0m [0;32mand[0m [0mswmr_support[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    172[0m             [0mflags[0m [0;34m|=[0m [0mh5f[0m[0;34m.[0m[0mACC_SWMR_READ[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 173[0;31m         [0mfid[0m [0;34m=[0m [0mh5f[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mname[0m[0;34m,[0m [0mflags[0m[0;34m,[0m [0mfapl[0m[0;34m=[0m[0mfapl[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    174[0m     [0;32melif[0m [0mmode[0m [0;34m==[0m [0;34m'r+'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    175[0m         [0mfid[0m [0;34m=[0m [0mh5f[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mname[0m[0;34m,[0m [0mh5f[0m[0;34m.[0m[0mACC_RDWR[0m[0;34m,[0m [0mfapl[0m[0;34m=[0m[0mfapl[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32mh5py/_objects.pyx[0m in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

[0;32mh5py/_objects.pyx[0m in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

[0;32mh5py/h5f.pyx[0m in [0;36mh5py.h5f.open[0;34m()[0m

[0;31mOSError[0m: Unable to open file (truncated file: eof = 40501248, sblock->base_addr = 0, stored_eof = 244871467)
OSError: Unable to open file (truncated file: eof = 40501248, sblock->base_addr = 0, stored_eof = 244871467)

